git clone git@github.com:nearform/aws-ami-container.git
git clone git@github.com:mcollina/aws-r53-container.git
git clone git@github.com:nearform/aws-elb-container.git
git clone git@github.com:nearform/docker-container.git
git clone git@github.com:nearform/nscale-docker-analyzer.git
git clone git@github.com:nearform/blank-container.git
git clone git@github.com:nearform/nscale.git
git clone git@github.com:nearform/nscale-aws-analyzer.git
git clone git@github.com:nearform/nscale-local-analyzer.git
git clone git@github.com:nearform/nscale-client.git
git clone git@github.com:nearform/nscale-kernel.git
git clone git@github.com:nearform/nscale-noauth.git
git clone git@github.com:nearform/nscale-protocol.git
git clone git@github.com:nearform/nscale-planner.git
git clone git@github.com:nearform/nscale-sdk.git
git clone git@github.com:nearform/nscale-util.git
git clone git@github.com:nearform/nscale-web.git
git clone git@github.com:nearform/nscale-api.git
git clone git@github.com:nearform/process-container.git
git clone git@github.com:nearform/nscale-compiler.git
git clone git@github.com:nearform/aws-sg-container.git
git clone git@github.com:nearform/nscale-docker-ssh-analyzer.git
git clone git@github.com:nearform/nscale-direct-analyzer.git
git clone git@github.com:mcollina/remote-forwarder.git
git clone git@github.com:mcollina/nscale-chaos-monkey.git
